# Analyser le fichier mock_credit_card_transactions.csv

In [1]:
import pandas as pd

# Charger le fichier CSV
df = pd.read_csv("../../Big_Data/mock_credit_card_transactions.csv")

# Afficher les premières lignes
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,12.4,0.23,-1.54,0.67,-0.12,1.84,-2.31,0.05,-0.77,1.12,...,1.93,-0.31,0.12,-0.44,1.11,-0.98,0.67,-1.29,42.50,0
1,36.8,-0.15,0.64,-1.02,1.25,-0.72,2.11,-0.08,0.44,-0.96,...,-0.41,0.95,-0.22,1.06,-0.34,0.77,-1.08,0.46,128.90,0
2,91.2,0.92,-0.46,1.14,-0.29,0.67,-0.83,1.05,-1.21,0.38,...,0.54,-0.61,1.04,-0.29,0.71,-0.82,1.18,-0.54,230.10,0
3,150.0,-1.23,0.97,-0.64,1.41,-0.98,0.52,-1.62,0.37,-0.45,...,-0.77,1.11,-0.51,0.92,-1.02,0.58,-0.73,1.05,15.20,0
4,210.7,0.31,-0.89,1.22,-0.54,0.99,-1.33,0.72,-0.29,1.56,...,0.58,-0.77,1.15,-0.33,0.79,-1.18,0.64,-0.92,320.75,0

In [2]:
# Compter les classes
class_counts = df['Class'].value_counts()

print("Distribution des classes :")
print(class_counts)

Distribution des classes :
Class
0    979
1     21
Name: count, dtype: int64

In [2]:
import pandas as pd

# Recharger le fichier original
df = pd.read_csv("../../Big_Data/mock_credit_card_transactions.csv")

# Supprimer la colonne Class
df_no_class = df.drop(columns=["Class"])

# Sauvegarder le nouveau fichier
df_no_class.to_csv("../../Big_Data/mock_credit_card_transactions_no_class.csv", index=False)

print("Fichier créé :", df_no_class.shape)

Fichier créé : (1000, 30)

In [3]:
df_no_class.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,12.4,0.23,-1.54,0.67,-0.12,1.84,-2.31,0.05,-0.77,1.12,...,-1.57,1.93,-0.31,0.12,-0.44,1.11,-0.98,0.67,-1.29,42.50
1,36.8,-0.15,0.64,-1.02,1.25,-0.72,2.11,-0.08,0.44,-0.96,...,1.40,-0.41,0.95,-0.22,1.06,-0.34,0.77,-1.08,0.46,128.90
2,91.2,0.92,-0.46,1.14,-0.29,0.67,-0.83,1.05,-1.21,0.38,...,-1.12,0.54,-0.61,1.04,-0.29,0.71,-0.82,1.18,-0.54,230.10
3,150.0,-1.23,0.97,-0.64,1.41,-0.98,0.52,-1.62,0.37,-0.45,...,0.63,-0.77,1.11,-0.51,0.92,-1.02,0.58,-0.73,1.05,15.20
4,210.7,0.31,-0.89,1.22,-0.54,0.99,-1.33,0.72,-0.29,1.56,...,-0.90,0.58,-0.77,1.15,-0.33,0.79,-1.18,0.64,-0.92,320.75

In [5]:
from kafka import KafkaProducer
import pandas as pd
import json
import time

# Charger le CSV sans Class
df = pd.read_csv("../../Big_Data/mock_credit_card_transactions_no_class.csv")
# df = pd.read_csv("../../test_transactions_no_class/Data_no_class.csv")

# Créer le producer Kafka
producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda v: json.dumps(v).encode("utf-8")
)

topic_name = "credit-card-transactions"

# Envoyer chaque ligne comme un message Kafka
for _, row in df.iterrows():
    message = row.to_dict()
    producer.send(topic_name, value=message)
    
    time.sleep(0.5)  # simulation streaming temps réel

producer.flush()
producer.close()

KeyboardInterrupt: